version: "2"
services:
  server:
    restart: always
    build: ./
    ports:
      - "1337:1337"
    volumes:
      - ./:/server
  mongo:
    container_name: paskachat-db
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
